### ISSUE TITLE
ANE build for iPhone - x64 and AMR include both architectures 

### ISSUE THREAD

**Issue by mspdevelopers** [BranchMetrics/air-plugin#12]
The current .ane uploaded to the repository has some inconsistencies regarding what the iphone-x86 and iphone-arm contain.
 Each iPhone (x86 and arm) folders contain a *.a file that includes some files related to the architecture, in this case we can see that both (x86 and arm) are containing each other, that means that we have double amount of files and as result of that a bigger ane file.

**Arm**
![image](https://cloud.githubusercontent.com/assets/10166083/23986469/9311c6d2-0a24-11e7-9f03-1d19bea17610.png)

**X86**
![image](https://cloud.githubusercontent.com/assets/10166083/23986480/a7af5e06-0a24-11e7-8d3a-c3dc17a0e219.png)

The preferred solution would be to only have the specific files for the architecture in each of the *.a file 

**Arm Example**
![image](https://cloud.githubusercontent.com/assets/10166083/23986654/866bfd8e-0a25-11e7-9593-022c3b69582b.png)

**X86 Example**
![image](https://cloud.githubusercontent.com/assets/10166083/23986624/67ef511c-0a25-11e7-823a-cf7f23c8712d.png)

**Comment by hasaudrey** [comment]
Thank you for letting us know! I created a ticket in our backlog to get this fixed. We just did an update recently so it might be a little while until we come back around to updating this plugin.

In the meantime the workaround would be for you to build the ANE yourself.

**Comment by HasRonald** [comment]
Hi, the latest release (5.1.1) has the static libraries separated out for iPhoneARM and iPhone-x86.

Please download the newest ANE and let us know if you run into any problems.

Thanks.
